tz_dashboard:
    resource: "@AdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /

tz_niveau:
    resource: "@AdminBundle/Resources/config/routing/niveau.yml"
    prefix:   /niveau

tz_classe:
    resource: "@AdminBundle/Resources/config/routing/classe.yml"
    prefix:   /classe